name = "momopix"
main = "src/index.ts"
minify = true
compatibility_date = "2024-11-23"

compatibility_flags = [ "nodejs_compat" ]

[vars]
CORS_ORIGIN = "https://img.zla.app"

# wrangler.toml (wrangler v3.88.0^)
[observability]
enabled = true
head_sampling_rate = 1

# Remember to set the following secrets in Workers Secrets

# TOKEN = "YOUR PRIVATE TOKEN"
