name = "momopix"
main = "src/index.ts"
minify = true
compatibility_date = "2024-11-23"

compatibility_flags = [ "nodejs_compat" ]

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = 'zla-img'

# Remember to set the following secrets in Workers Secrets

# TOKEN = "YOUR PRIVATE TOKEN"

# wrangler.toml (wrangler v3.88.0^)
[observability]
enabled = true
head_sampling_rate = 1
