const ITEMS_PER_PAGE_OPTIONS = [10, 20, 30];

const MAX_FILE_SIZE_MB = 5;
const MAX_FILES = 10;

const MAX_HEIGHT = 1440;
const MAX_WIDTH = 2560;

export {
  ITEMS_PER_PAGE_OPTIONS,
  MAX_FILE_SIZE_MB,
  MAX_FILES,
  MAX_HEIGHT,
  MAX_WIDTH,
};
